### ISSUE TITLE
Multiple keys for same URL

### ISSUE THREAD

**Issue by iamdevnull** [pauloamgomes/CockpitCMS-RedisCache#1]
Hello,

after activating the redis addon by:

config.php

```
if (!empty(getenv('COCKPIT_CACHE_SERVER'))){
  $configs['redis'] = [
    "host"  => getenv('COCKPIT_CACHE_SERVER'),
    "port"  => '6379',
    "bypass_token" => '123456',
    "prefix" => 'cockpit-cms-testing',
    "cache_paths" => ["/api/collections/get/X" => '60', "/api/collections/get/Y" => '60', "/api/collections/get/Z" => '10']
  ];
}
```
everything seems to be fine. After a little bit of debugging i recognized that every request with SAME URL generates a new redis key.

Is this behavior ok?

**Comment by pauloamgomes** [comment]
Hi @m-osmani , can't replicate the issue! Are you passing any dynamic query parameter in the request? The key is created with a hash of the full request, so any parameter that changes (GET or POST) will be a new key.

**Comment by iamdevnull** [comment]
Hi @pauloamgomes thx for your reply.

My URL looks like this:

https://www.example.com/api/collections/get/Deal?token=c1699c536f86beee51237231bf2456

Deal is a collection with 10 fields.

![image](https://user-images.githubusercontent.com/10820634/66191591-0465c100-e68f-11e9-9398-032f6a5b1751.png)

**Comment by pauloamgomes** [comment]
Ok, the request seems fine, what you see on the admins page for redis, e.g.:

<img width="1637" alt="image" src="https://user-images.githubusercontent.com/102261/66193833-5278c580-e68b-11e9-8fb3-f9f8e7c0975e.png">

multiple keys?

**Comment by iamdevnull** [comment]
My test collection with one entry:

1.) first request
URL: https://www.example.com/api/collections/get/test?token=c1699c536f86beee51237231bf25f4

Response-Body:
```
{
    "fields": {
        "test": {
            "name": "test",
            "type": "text",
            "localize": false,
            "options": []
        }
    },
    "entries": [
        {
            "_id": "5d9365ab07868d433e7727d2",
            "test": "adsad",
            "_mby": "5d1218ad333732001300004e",
            "_by": "5d1218ad333732001300004e",
            "_modified": 1569940907,
            "_created": 1569940907
        }
    ],
    "total": 1
}
```
![cockpit-redis-1](https://user-images.githubusercontent.com/10820634/66198792-7513da00-e69d-11e9-966f-4b25d5373693.png)



2.) second request with same url
URL: https://www.example.com/api/collections/get/test?token=c1699c536f86beee51237231bf25f4

```
{
    "fields": {
        "test": {
            "name": "test",
            "type": "text",
            "localize": false,
            "options": []
        }
    },
    "entries": [
        {
            "_id": "5d9365ab07868d433e7727d2",
            "test": "adsad",
            "_mby": "5d1218ad333732001300004e",
            "_by": "5d1218ad333732001300004e",
            "_modified": 1569940907,
            "_created": 1569940907
        }
    ],
    "total": 1
}
```

![cockpit-redis-2](https://user-images.githubusercontent.com/10820634/66198806-79d88e00-e69d-11e9-9ae2-010df0e03513.png)

**Comment by pauloamgomes** [comment]
That's a bit weird, as I said, the key is based on the request parameters, can you confirm that your server/proxy is not modifying the request before it reaches cockpit?

You can try to check the $_REQUEST array on the addon rest.php file, e.g.:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/102261/66200301-a3db8180-e698-11e9-8a69-f97ac8c8c97b.png">

and see if you have something that was injected by the server

**Comment by iamdevnull** [comment]
Thx for your help. 

My setup: AWS-ALB -> ECS -> MongoDB & Redis for Cache

This is the result, maybe you have an idea:

```
1.)

Array
(
    [token] => c1699c536f86beee51237231bf25f4
    [dtCookie] => v_4_srv_3_sn_A1EAE1716170235FC1E489082D61B0E7_perc_100000_ol_0_mul_1
    [AWSALB] => JKXNwuUBf d4 Dz8fNSYUEH/rJGrczTC/gtaDligc9pmR  FGlVZBH5vBPB9zbAxGi/8fxofrCG9462SNVpsvyBO7twOp3v6w0zkKkmQh33WNUiTi srNbjClR2/
)

2.)

Array
(
    [token] => c1699c536f86beee51237231bf25f4
    [dtCookie] => v_4_srv_3_sn_A1EAE1716170235FC1E489082D61B0E7_perc_100000_ol_0_mul_1
    [AWSALB] => /Z6xPkhZrRWyauA2SL9OnlyQ71hBPjkDjeRxtd1Bv/Cm/Kmc29uWSo8BZDnQ644XWbDckFp1mjQsuOD3 s 97R0mPYk0UEq/xUyQUAd9ySCw7cnN GtKRaWD1yqp
)

```

**Comment by iamdevnull** [comment]
@pauloamgomes the cause for the multiple keys is the activation of the so called "Sticky Sessions" inside a "Target Group". https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.html

After after disabling the "Sticky Sessions" everything works as expected.

How does Cockpit manage User sessions? Local or DB?

I want to scale Cockpit with ECS (multiple Container) thats why it is important to know if it is enough to have the DB in Mongo and the Cache in Redis and a shared "storage" folder over EFS.

**Comment by pauloamgomes** [comment]
Yeah, that was the issue, in such case provided an improvement in the addon settings, so you can exclude some parameters form the request of being used in the generated redis key, on the config you can use:

```yaml
redis:
 ...
  cache_request_ignore:
    - AWSALB
```

**Comment by iamdevnull** [comment]
thanks for your support!

**Comment by iamdevnull** [comment]
Last question. I am using the config.php of cockpit and not the config.yaml because i need dynamic env vars. Can you check plz if my syntax is correct concerning the new setting:

```
if (!empty(getenv('COCKPIT_CACHE_SERVER'))){
  $configs['redis'] = [
    "host"  => getenv('COCKPIT_CACHE_SERVER'),
    "port"  => '6379',
    "bypass_token" => '123456',
    "prefix" => 'cockpit-cms-testing',
    "cache_paths" => ["/api/collections/get/X" => '60', "/api/collections/get/Y" => '60', "/api/collections/get/Z" => '10'],
    "cache_request_ignore" =>  'AWSALB'
  ];
}
```

**Comment by pauloamgomes** [comment]
if using config.php it should be an array, e.g.:

```php
if (!empty(getenv('COCKPIT_CACHE_SERVER'))){
  $configs['redis'] = [
    "host"  => getenv('COCKPIT_CACHE_SERVER'),
    "port"  => '6379',
    "bypass_token" => '123456',
    "prefix" => 'cockpit-cms-testing',
    "cache_paths" => ["/api/collections/get/X" => '60', "/api/collections/get/Y" => '60', "/api/collections/get/Z" => '10'],
    "cache_request_ignore" => ['AWSALB']
  ];
}
```
